### ISSUE TITLE
Script is never unblocked

### ISSUE THREAD

**Issue by mgrundkoetter** [sandstorm/Sandstorm.CookiePunch#3] opened 2021-01-22 16:21 UTC
We use the NEOS package "WebExcess.OpenStreetMap" on the website (just an example). Integration as in their readme.
Now we added the CookiePunch (also as in readme) and use this config:

```yaml
Sandstorm:
  CookiePunch:
    consent:
      privacyPolicyUrl: "/de/meta/datenschutz"
      storageMethod: cookie
      cookieName: cookie_punch
      cookieExpiresAfterDays: 30
      mustConsent: true
      acceptAll: true
      hideDeclineAll: false
      default: false
    purposes:
      mediaembeds: "Einbindung von externen Medien"
    groups:
      default:
        title: "notwendige Cookies"
        description: "Speichert Ihre Cookie-Auswahl, sowie weitere technisch notwendige Einstellungen."
        consent:
          required: true
      media:
        title: "externen Medien"
        purposes:
          - mediaembeds
        description: "Videos von YouTube oder Vimeo, Kartendaten von OpenStreetMaps."
        consent:
          default: false
    elements:
      patterns:
        "Packages/Neos.Neos":
          type: script
          block: false
          group: default
        "Packages/Networkteam.Neos.MailObfuscator":
          type: script
          block: false
          group: default
        "https://www.youtube.com/embed/":
          type: iframe
          block: true
          group: media
        "Packages/WebExcess.OpenStreetMap":
          type: script
          block: true
          group: media
        "openstreetmap.org":
          type: script
          block: true
          group: media
```

The cookie banner is shown as expected, everything looks fine. All the "default" scripts also appear as normal in the html source code. The problem is, that even after activating the "media" group (with or without reloading the page), the Main.js file still remains blocked:

```html
<script data-src="https://xyz.local/_Resources/Static/Packages/WebExcess.OpenStreetMap/Assets/Main.js" data-name="media">
```

Am I missing something in the configuration? I can't get the "unblock" step to work :-( What am I doing wrong?

**Comment by fheinze** [comment] 2021-01-26 15:04
Unblocking is done by Klaro Consent Manager. Are there any JS-Errors in the console? 

Could you run the following command in the inspector and check if the value changes when switching between "on" and "off" for the media group in the consent modal. You can easily open the modal with `window.klaro.show()`

```javascript
window.klaro.getManager().getConsent("media")
```

**Comment by mgrundkoetter** [comment] 2021-01-26 16:32
The result, if I accepted all the groups is:
```
window.klaro.getManager().getConsent("media")
true
```

This is also correct in the UI dialogue. There are no errors in the JS console. The Element Browser shows this html if I did not accept:
```html
<script data-src="https://xyz.local/_Resources/Static/Packages/WebExcess.OpenStreetMap/Assets/Main.js" data-name="media" type="text/plain" id="" async="" style=""></script>
```
and after I accepted it looks like this:

```html
<script data-src="https://xyz.local/_Resources/Static/Packages/WebExcess.OpenStreetMap/Assets/Main.js" data-name="media" type="undefined" id="" async="" src="https://xyz.local/_Resources/Static/Packages/WebExcess.OpenStreetMap/Assets/Main.js" style=""></script>
```

The Main.js is never loaded, says the network tab, no matter what I chose in the klaro dialogue.

**Comment by fheinze** [comment] 2021-01-27 10:00
I was able to reproduce this Bug. Klaro seems to look for a corresponding data attribute to "repair" the tags.

```html
<script data-src="index.js" data-type="application/javascript" type="text/plain"></script>
```
Can be repaired as Klaro know what the original type was. 

```html
<script data-src="index.js" type="text/plain"></script>
```
This fails and will lead to this markup
```html
<script data-src="index.js" type="undefined"></script>
```
Because it cannot recover the original type.

This needs to be fixed in CookiePunch. We actually don't need to set a type="text/plain" if a src is present but for consistency reasons I would rather just add a data-type so that Klaro does not recover this attribute to undefined.

**Closed** 2021-01-28 09:46 UTC
